In [1]:
import numpy as np
from matplotlib import pyplot as pp
import numpy.linalg as alg
from mpl_toolkits import mplot3d # a three-dimensional axes can be created

# this is the script for linear regressino with multiple variable

In [8]:
data=open('ex1data2.txt','r').readlines()

In [9]:
X1=[float(elem.split(',')[0]) for elem in data]
X2=[float(elem.split(',')[1]) for elem in data]
y=[float(elem.split(',')[2])  for elem in data]
X=np.c_[X1,X2]
m=len(y)

In [10]:
print ('First 10 examples from the dataset: \n')
[print ('X1= %.0f. X2= %.0f \n' % (X1[i],X2[i])) for i in range(0,9)]

First 10 examples from the dataset: 

X1= 2104. X2= 3 

X1= 1600. X2= 3 

X1= 2400. X2= 3 

X1= 1416. X2= 2 

X1= 3000. X2= 4 

X1= 1985. X2= 4 

X1= 1534. X2= 3 

X1= 1427. X2= 3 

X1= 1380. X2= 3 



[None, None, None, None, None, None, None, None, None]

array([[2.104e+03, 3.000e+00],
       [1.600e+03, 3.000e+00],
       [2.400e+03, 3.000e+00],
       [1.416e+03, 2.000e+00],
       [3.000e+03, 4.000e+00],
       [1.985e+03, 4.000e+00],
       [1.534e+03, 3.000e+00],
       [1.427e+03, 3.000e+00],
       [1.380e+03, 3.000e+00],
       [1.494e+03, 3.000e+00],
       [1.940e+03, 4.000e+00],
       [2.000e+03, 3.000e+00],
       [1.890e+03, 3.000e+00],
       [4.478e+03, 5.000e+00],
       [1.268e+03, 3.000e+00],
       [2.300e+03, 4.000e+00],
       [1.320e+03, 2.000e+00],
       [1.236e+03, 3.000e+00],
       [2.609e+03, 4.000e+00],
       [3.031e+03, 4.000e+00],
       [1.767e+03, 3.000e+00],
       [1.888e+03, 2.000e+00],
       [1.604e+03, 3.000e+00],
       [1.962e+03, 4.000e+00],
       [3.890e+03, 3.000e+00],
       [1.100e+03, 3.000e+00],
       [1.458e+03, 3.000e+00],
       [2.526e+03, 3.000e+00],
       [2.200e+03, 3.000e+00],
       [2.637e+03, 3.000e+00],
       [1.839e+03, 2.000e+00],
       [1.000e+03, 1.000e+00],
       [

In [5]:
def featureNormalize(X):
    X_norm=X
    mu=np.zeros((1,X.shape[1]),'d')
    sigma=np.zeros((1,X.shape[1]),'d')
    
    column_x=X.shape[1]
    for i in range(0,column_x):
        mu[0,i]= np.mean(X[:,i])
        
    for i in range(0,column_x):
        sigma[0,i]=np.std(X[:,i],ddof=1) # the sample standard deviation!!
        
    for i in range(0,column_x):
        X_norm[:,i]=(X[:,i]-mu[0,i])/sigma[0,i]
    
    return X_norm, mu, sigma

In [6]:
X, mu, sigma=featureNormalize(X)
X, mu, sigma

(array([[ 1.30009869e-01, -2.23675187e-01],
        [-5.04189838e-01, -2.23675187e-01],
        [ 5.02476364e-01, -2.23675187e-01],
        [-7.35723065e-01, -1.53776691e+00],
        [ 1.25747602e+00,  1.09041654e+00],
        [-1.97317285e-02,  1.09041654e+00],
        [-5.87239800e-01, -2.23675187e-01],
        [-7.21881404e-01, -2.23675187e-01],
        [-7.81023044e-01, -2.23675187e-01],
        [-6.37573110e-01, -2.23675187e-01],
        [-7.63567023e-02,  1.09041654e+00],
        [-8.56737193e-04, -2.23675187e-01],
        [-1.39273340e-01, -2.23675187e-01],
        [ 3.11729182e+00,  2.40450826e+00],
        [-9.21956312e-01, -2.23675187e-01],
        [ 3.76643089e-01,  1.09041654e+00],
        [-8.56523009e-01, -1.53776691e+00],
        [-9.62222960e-01, -2.23675187e-01],
        [ 7.65467909e-01,  1.09041654e+00],
        [ 1.29648433e+00,  1.09041654e+00],
        [-2.94048269e-01, -2.23675187e-01],
        [-1.41790005e-01, -1.53776691e+00],
        [-4.99156507e-01, -2.236

In [105]:
theta=np.zeros((3,1),'d')
y=np.asarray(y)
y.shape=(m,1)
one=np.ones((m,1),'d')
X=np.c_[one,X]

In [106]:
alpha=0.01
num_iters=400

In [107]:
def computeCostMulti(X,y,theta):
    #X is the "design matrix" containing our training examples.
    # y is the class labels
    #m=np.shape(X)[0]  # number of training number
    predictions=np.dot(X,theta)  # predictions of hypothesis on all m examples
    sqrErrors=(predictions-y)*(predictions-y) # squared errors

    J=np.sum(sqrErrors)/(2*m)
    return J

In [108]:
computeCostMulti(X,y,theta)

65591548106.45744

In [109]:
# this function is not correct, should be updated. 

def gradientDescentMulti(X,y,theta,alpha,num_iters):
    # this is the function to perform gradient descent to learn
    #theta
    m=len(y)
    J_history=np.zeros((num_iters,1),'d')
    #X1=np.delete(X,np.s_[0],1)  # remove the first column of matrix
    
    
    for iter in range(1,num_iters+1):
        predictions=np.dot(X,theta)
        deriv0=predictions-y
        deriv1=np.zeros((m,X.shape[1]),'d')
        tempo1=np.zeros((X.shape[1],1),'d')
        
        for i in range (0,X.shape[1]):        
            tempo1[i,0]=np.sum(deriv0.T*X[:,i]) # be careful the internal multiplication. a transpose is needed.
            
        theta=theta-alpha*(1/m)*tempo1
        J_history[iter-1]=computeCostMulti(X,y,theta)
    return theta, J_history

m=len(y)
J_history=np.zeros((num_iters,1),'d')

for iter in range(1,num_iters+1):
    predictions=np.dot(X,theta)
    deriv0=predictions-y
    deriv1=np.zeros((m,X.shape[1]),'d')
    tempo1=np.zeros((X.shape[1],1),'d')
    
    for i in range (0,X.shape[1]):
        deriv1[:,i]=deriv0.reshape(m,)*X[:,i]
        tempo1[i]=np.sum(deriv1[:,i])       
        
    theta=theta-alpha/m*tempo1
    
    J_history[iter-1]=computeCostMulti(X,y,theta)


In [110]:
theta, J_histrory=gradientDescentMulti(X,y,theta,alpha,num_iters)
prediction1=np.dot(np.array([1,1650,3]), theta)
print (theta)

[[334302.06399328]
 [100087.11600585]
 [  3673.54845093]]


In [111]:
data=open('ex1data2.txt','r').readlines()
X1=[float(elem.split(',')[0]) for elem in data]
X2=[float(elem.split(',')[1]) for elem in data]
y=[float(elem.split(',')[2])  for elem in data]
X=np.c_[X1,X2]
m=len(y)
one=np.ones((m,1),'d')
X=np.c_[one,X]

def normalEqn(X,y):
    theta=np.zeros((X.shape[1],1),'d')
    XTX=np.dot((np.transpose(X)),X)
    inv_XTX=alg.inv(XTX)
    inv_XTXXT=np.dot(inv_XTX,np.transpose(X))
    theta=np.dot(inv_XTXXT,y)
    return theta

In [112]:
theta=normalEqn(X,y)
theta

array([89597.9095428 ,   139.21067402, -8738.01911233])

In [113]:
prediction2=np.dot(np.array([1,1650,3]), theta)
print (prediction2)

293081.4643348959
